<Project Sdk="Microsoft.NET.Sdk" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  
  <PropertyGroup>
    <AnalysisLevel>preview-all</AnalysisLevel>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <TargetFramework>net11.0</TargetFramework>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <Platforms>x64</Platforms>
  </PropertyGroup>
  
  <ItemGroup>
    <None Remove="UnitTest.csproj.lscache" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.1.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="Newtonsoft.Json" Version="14.0.1-beta2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Roslynator.Analyzers" Version="5.0.1" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" />
    <PackageReference Include="Roslynator.CodeFixes" Version="5.0.1" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <!-- <ProjectReference Include="..\..\Plant VNC\VNCChecker.csproj" /> -->
    <ProjectReference Include="..\Common\Common.csproj" />
    <!-- <ProjectReference Include="..\FormObjectViewer\FormObjectViewer.csproj" /> -->
    <ProjectReference Include="..\Parser\Parser.csproj" />
    <ProjectReference Include="..\Specification.INI\Specification.INI.csproj" />
    <ProjectReference Include="..\Specification.IPL\Specification.IPL.csproj" />
    <ProjectReference Include="..\Specification.JSON\Specification.JSON.csproj" />
    <ProjectReference Include="..\Specification.REG\Specification.REG.csproj" />
    <ProjectReference Include="..\Specification.WAD\Specification.WAD.csproj" />
    <ProjectReference Include="..\Specification.XML\Specification.XML.csproj" />
    <ProjectReference Include="..\Specification.ZDoom\Specification.ZDoom.csproj" />
    <!-- <ProjectReference Include="..\TestConsole\TestConsole.csproj" /> -->
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
