<Project Sdk="Microsoft.NET.Sdk" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup>
    <AnalysisLevel>preview-all</AnalysisLevel>
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <StartupObject>TestConsole.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Roslynator.Analyzers" Version="5.0.1" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" />
    <PackageReference Include="Roslynator.CodeFixes" Version="5.0.1" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\Parser\Parser.csproj" />
    <ProjectReference Include="..\Specification.INI\Specification.INI.csproj" />
    <ProjectReference Include="..\Specification.IPL\Specification.IPL.csproj" />
    <ProjectReference Include="..\Specification.JSON\Specification.JSON.csproj" />
    <ProjectReference Include="..\Specification.REG\Specification.REG.csproj" />
    <ProjectReference Include="..\Specification.WAD\Specification.WAD.csproj" />
    <ProjectReference Include="..\Specification.XML\Specification.XML.csproj" />
    <ProjectReference Include="..\Specification.ZDoom\Specification.ZDoom.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Paths.Designer.cs">
      <DependentUpon>Paths.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Paths.resx">
      <LastGenOutput>Paths.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>

</Project>
